
const $=id=>document.getElementById(id);
const BASE={lat:40.6096,lon:9.7514,label:"La Caletta"};
let state={intent:"snorkeling",originMode:"base",manualOrigin:null,userLocation:null,windMode:"Automatico dal meteo",autoWind:"Mare calmo",effectiveWind:"Mare calmo",walkMax:25,driveMax:180,crowd:"Tranquillo",sortMode:"best",personalPref:"balanced",withinDriveOnly:true,hideVisited:false,favoritesOnly:false,query:"",quickFilter:""};
const icon={"Snorkeling elite":"🤿","Snorkeling PRO":"🐠","Calette nascoste":"🏝️","Spiagge top":"🏖️","Panorami/foto":"📸","Escursioni/gommoni":"🚤","Cibo/pesce":"🍝","Parcheggi/accessi":"🅿️","Spiagge famose":"⭐","Spiagge famose Nord":"💎","Spiagge famose Sud":"🌅","Iconiche Golfo Orosei":"🌊","Spiagge Sardegna Nord-Ovest":"🧭","Spiagge Sardegna Nord":"🧭","Spiagge Sardegna Ovest":"🌊","Spiagge Sardegna Sud-Ovest":"🌅","Spiagge Sardegna Sud":"🌞","Spiagge Sardegna Sud-Est":"🌞","Spiagge Sardegna Est":"🌊"};
const mapsIcon='<svg class="mapicon" viewBox="0 0 24 24"><path fill="#34a853" d="M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7z"/><circle fill="#fff" cx="12" cy="9" r="2.5"/></svg>';
const wazeIcon='<svg class="mapicon" viewBox="0 0 24 24"><path fill="#33ccff" d="M20 11.5c0-4.1-3.6-7.5-8-7.5s-8 3.4-8 7.5c0 1.5.5 2.9 1.4 4.1L3 18h3.6c1.4.7 3.2 1 5.4 1 4.4 0 8-3.4 8-7.5z"/><circle cx="9" cy="11" r="1"/><circle cx="15" cy="11" r="1"/><path d="M9 15c2 1 4 1 6 0" stroke="#111" fill="none" stroke-width="1.5"/></svg>';
let marine={wave:null,uv:null,water:null};
function loadLocal(){try{const s=JSON.parse(localStorage.getItem("sardegna-v7")||"{}");PLACES.forEach(p=>{if(s.favorites?.[p.id])p.favorite=true;if(s.visited?.[p.id])p.visited=true;if(s.notes?.[p.id])p.personalNote=s.notes[p.id];});}catch(e){}}
function saveLocal(){const favorites={},visited={},notes={};PLACES.forEach(p=>{if(p.favorite)favorites[p.id]=true;if(p.visited)visited[p.id]=true;if(p.personalNote)notes[p.id]=p.personalNote;});localStorage.setItem("sardegna-v7",JSON.stringify({favorites,visited,notes}));}
function hav(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180;const dp=rad(c-a),dl=rad(d-b);const q=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function origin(){if(state.originMode==="gps"&&state.userLocation)return state.userLocation;if((state.originMode==="manual"||state.originMode==="preset")&&state.manualOrigin)return state.manualOrigin;return BASE}
function dist(p){const o=origin();return hav(o.lat,o.lon,p.lat,p.lon)}
function drive(p){return Math.round((dist(p)*1.38/62)*60+8)}
function marineScore(p){let s=10;if(marine.wave!=null){if(marine.wave>1.2)s-=3;else if(marine.wave>.7)s-=1.5}if((p.windAvoid||"").includes(state.effectiveWind))s-=2;if((p.windOK||"").includes(state.effectiveWind))s+=.7;return Math.max(0,Math.min(10,Math.round(s*10)/10))}
function intentScore(p){const i=state.intent;let s=0;if(i==="snorkeling")s+=p.snorkeling*2.2+(String(p.tags||"").includes("snorkeling")?5:0);if(i==="wow")s+=p.wow*2+p.waterColor;if(i==="quiet")s+=(p.crowdTarget==="Tranquillo"?18:0)+(p.level==="L1 Local"?6:0);if(i==="famous")s+=(String(p.tags||"").includes("famosa")?18:0)+p.wow;if(i==="near")s-=drive(p)/3;if(i==="couple")s+=p.wow*1.2-(p.walkMin>25?8:0)-(p.crowdTarget==="Affollato"?5:0);return s}
function textScore(p,q){if(!q)return 0;q=q.toLowerCase();const hay=`${p.name} ${p.category} ${p.zone} ${p.fauna} ${p.notes} ${(p.tags||[]).join(" ")}`.toLowerCase();let s=0;q.split(/\s+/).filter(Boolean).forEach(w=>{if(hay.includes(w))s+=8;if(p.name.toLowerCase().includes(w))s+=15});if(q.includes("polp")&&hay.includes("polp"))s+=20;if(q.includes("barracuda")&&hay.includes("barracuda"))s+=20;if(q.includes("liberotto")&&p.name.toLowerCase().includes("liberotto"))s+=50;return s}
function why(p){let bits=[];if(state.intent==="snorkeling"&&p.snorkeling>=7)bits.push("fondali buoni");if((p.windOK||"").includes(state.effectiveWind))bits.push("vento adatto");if(p.wow>=9)bits.push("mare spettacolare");if(drive(p)<=state.driveMax)bits.push("entro il tempo auto");if(p.walkMin<=state.walkMax)bits.push("camminata ok");if(p.crowdTarget===state.crowd)bits.push("folla coerente");return bits.slice(0,4).join(" · ")||"buon compromesso"}
function score(p){let s=p.wow*1.5+p.snorkeling*.8+marineScore(p)+intentScore(p)+textScore(p,state.query)+textScore(p,state.quickFilter);if((p.windOK||"").includes(state.effectiveWind))s+=6;if((p.windAvoid||"").includes(state.effectiveWind))s-=10;s+=(p.walkMin<=state.walkMax)?5:-7;const dm=drive(p);s+=(dm<=state.driveMax)?8:-(dm-state.driveMax)/2;if(state.crowd!=="Indifferente")s+=(p.crowdTarget===state.crowd)?4:-2;if(state.withinDriveOnly&&dm>state.driveMax)s-=1000;if(state.hideVisited&&p.visited)s-=100;if(state.favoritesOnly&&!p.favorite)s-=100;return Math.round(s*10)/10}
function results(){let arr=PLACES.map(p=>({...p,aiScore:score(p),distanceKm:dist(p),driveMin:drive(p),marineScore:marineScore(p)})).filter(p=>p.aiScore>-50);if(state.sortMode==="distance")arr.sort((a,b)=>a.distanceKm-b.distanceKm);else if(state.sortMode==="wow")arr.sort((a,b)=>b.wow-a.wow||b.aiScore-a.aiScore);else if(state.sortMode==="snorkel")arr.sort((a,b)=>b.snorkeling-a.snorkeling||b.aiScore-a.aiScore);else arr.sort((a,b)=>b.aiScore-a.aiScore||a.distanceKm-b.distanceKm);return arr}
function gmaps(p){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.lat+","+p.lon)}&travelmode=driving`}
function waze(p){return `https://waze.com/ul?ll=${p.lat},${p.lon}&navigate=yes`}
function mcolor(c){if((c||"").includes("Snorkeling"))return"#38bdf8";if(c==="Calette nascoste")return"#22c55e";if(c==="Panorami/foto")return"#fb923c";if(c==="Cibo/pesce")return"#fb7185";if((c||"").includes("famose")||(c||"").includes("Iconiche")||(c||"").includes("Sardegna"))return"#fbbf24";return"#94a3b8"}
function makeIcon(p){return L.divIcon({className:"custom-marker",html:`<div style="width:30px;height:30px;border-radius:50%;background:${mcolor(p.category)};display:grid;place-items:center;border:2px solid white;box-shadow:0 8px 20px rgba(0,0,0,.35);font-size:16px">${icon[p.category]||"📍"}</div>`,iconSize:[30,30],iconAnchor:[15,15],popupAnchor:[0,-12]})}
let map,layer,userMarker;
function initMap(){map=L.map("map",{zoomControl:false}).setView([40.05,9.15],7);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(map);layer=L.layerGroup().addTo(map)}
function renderMarkers(list){layer.clearLayers();list.slice(0,180).forEach(p=>L.marker([p.lat,p.lon],{icon:makeIcon(p)}).addTo(layer).bindPopup(`<b>${icon[p.category]||"📍"} ${p.name}</b><br>${p.driveMin} min · AI ${p.aiScore}<br><button onclick="openDetail('${p.id}')">Apri</button>`))}
function render(){const list=results();$("totalPlaces").textContent=PLACES.length;$("resultsTitle").textContent=`Risultati · ${list.length}`;renderMarkers(list);$("results").innerHTML=list.slice(0,60).map((p,i)=>`<article class="card"><h4>${i+1}. ${icon[p.category]||"📍"} ${p.name}</h4><div class="meta">${p.zone} · ${p.category}<br>${p.distanceKm.toFixed(1)} km · 🚗 ${p.driveMin} min</div><div class="score"><span class="pill gold">AI ${p.aiScore}</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span><span class="pill">mare ${p.marineScore}/10</span></div><div class="meta">Perché: <b>${why(p)}</b></div><div class="actions"><button onclick="openDetail('${p.id}')">Scheda</button><a class="ghost" href="${gmaps(p)}" target="_blank">${mapsIcon}Maps</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a><button class="ghost" onclick="toggleFavorite('${p.id}')">${p.favorite?'★':'☆'} Preferito</button></div></article>`).join("")}
function today(){const p=results()[0];if(!p)return;$("todayChoice").classList.remove("hidden");$("todayChoice").innerHTML=`<h3>🏆 Oggi ti direi: ${p.name}</h3><div class="score"><span class="pill gold">AI ${p.aiScore}</span><span class="pill">🚗 ${p.driveMin} min</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span></div><p class="meta">Te la consiglio perché: ${why(p)}.</p><div class="actions"><button onclick="openDetail('${p.id}')">Apri scheda</button><a class="primary" href="${gmaps(p)}" target="_blank">${mapsIcon}Portami lì</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a></div>`;window.scrollTo({top:0,behavior:"smooth"})}
function openDetail(id){const p=PLACES.find(x=>x.id===id);if(!p)return;fetchWeather(p.lat,p.lon,p.name,false);$("placeDetail").innerHTML=`<div class="detail"><h2>${icon[p.category]||"📍"} ${p.name}</h2><p class="meta">${p.zone} · ${p.category}<br>${dist(p).toFixed(1)} km · 🚗 ${drive(p)} min</p><div class="score"><span class="pill gold">AI ${score(p)}</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span></div><div class="detail-grid"><div class="detail-box"><b>Perché</b>${why(p)}</div><div class="detail-box"><b>Fauna</b>${p.fauna||"-"}</div><div class="detail-box"><b>Vento OK</b>${p.windOK||"-"}</div><div class="detail-box"><b>Da evitare</b>${p.windAvoid||"-"}</div><div class="detail-box"><b>Ingresso</b>${p.entryTip||"-"}</div><div class="detail-box"><b>Parcheggio</b>${p.parking||"-"}</div></div><p>${p.notes||""}</p><textarea id="noteBox" placeholder="Nota personale / diario...">${p.personalNote||""}</textarea><div class="actions" style="margin-top:12px"><a class="primary" href="${gmaps(p)}" target="_blank">${mapsIcon}Google Maps</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a><button class="ghost" onclick="toggleFavorite('${p.id}')">${p.favorite?'★ Preferito':'☆ Preferito'}</button><button class="ghost" onclick="toggleVisited('${p.id}')">${p.visited?'Visitato ✓':'Segna visitato'}</button><button onclick="saveNote('${p.id}')">Salva nota</button></div></div>`;$("placeDialog").showModal()}
window.openDetail=openDetail;
function toggleFavorite(id){const p=PLACES.find(x=>x.id===id);if(p){p.favorite=!p.favorite;saveLocal();render()}}function toggleVisited(id){const p=PLACES.find(x=>x.id===id);if(p){p.visited=!p.visited;saveLocal();render()}}function saveNote(id){const p=PLACES.find(x=>x.id===id);if(p){p.personalNote=$("noteBox").value;saveLocal();render()}}window.toggleFavorite=toggleFavorite;window.toggleVisited=toggleVisited;window.saveNote=saveNote;
function chatSend(){const text=$("chatInput").value.trim();if(!text)return;$("chatLog").innerHTML+=`<div class="user">${text}</div>`;$("chatInput").value="";applyChat(text);const top=results().slice(0,3);let html=`<div class="bot"><b>Ok, ti cerco qualcosa così.</b><br>`;if(text.match(/snork|maschera|pesci|polp|barracuda/i))html+=`Ho dato più peso a snorkeling e fondali. `;if(text.match(/poca gente|tranquill|segre/i))html+=`Ho favorito posti meno affollati. `;if(text.match(/ragazza|coppia|romantic/i))html+=`Ho cercato posti belli ma non troppo stressanti. `;html+=`<br><br>Le migliori opzioni ora sono:<br>`+top.map((p,i)=>`${i+1}. <b>${p.name}</b> · ${p.driveMin} min · 🤿 ${p.snorkeling}/10 · WOW ${p.wow}/10<br><small>${why(p)}</small>`).join("<br>")+`<br><br>Puoi continuare: “più vicino”, “meno gente”, “più snorkeling”, “senza camminare”.</div>`;$("chatLog").innerHTML+=html;$("chatLog").scrollTop=$("chatLog").scrollHeight;render()}
function applyChat(t){const s=t.toLowerCase();state.query=s;$("smartSearch").value=s;if(s.match(/snork|maschera|pesci|polp|barracuda/))setIntent("snorkeling",false);if(s.match(/poca gente|tranquill|isolata|segre/))setIntent("quiet",false);if(s.match(/famos|principe|pelosa|brandinchi/))setIntent("famous",false);if(s.match(/ragazza|coppia|romantic|fidanzata/))setIntent("couple",false);if(s.match(/vicino|poco auto|meno macchina/))setIntent("near",false);const mins=s.match(/(\\d+)\\s*(min|minuti|ore|ora|h)/);if(mins){let n=Number(mins[1]);if(s.includes("ora")||s.includes("ore")||s.includes("h"))n*=60;state.driveMax=n;$("driveMax").value=Math.min(280,n);$("driveLabel").textContent=n+" min"}}
function setIntent(intent,doRender=true){state.intent=intent;document.querySelectorAll(".intent").forEach(b=>b.classList.toggle("active",b.dataset.intent===intent));if(doRender)render()}
function windName(deg,speed){if(speed>=25)return"Vento forte";if(deg==null)return"Mare calmo";let base=["N","NE","E","SE","S","SW","W","NW"][Math.round(deg/45)%8];if(base==="NW")return speed>=15?"Maestrale forte":"Maestrale leggero";if(base==="SE")return speed>=15?"Scirocco forte":"Scirocco leggero";if(base==="E")return"Levante forte";if(base==="W")return"Ponente leggero";return speed<8?"Mare calmo":"Vento forte"}
function windDir(deg){if(deg==null)return"-";return["N","NE","E","SE","S","SW","W","NW"][Math.round(deg/45)%8]}
async function fetchWeather(lat,lon,label="questa zona",update=true){try{let r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,wind_direction_10m,uv_index&forecast_days=1&timezone=auto`);let d=await r.json();let c=d.current||{};let sp=Math.round(c.wind_speed_10m||0);let auto=windName(c.wind_direction_10m,sp);$("weatherText").innerHTML=`<b>${label}</b>: ${Math.round(c.temperature_2m)}°C · vento ${sp} km/h da ${windDir(c.wind_direction_10m)} · <b>${auto}</b>`;if(update){state.autoWind=auto;$("autoWindLabel").textContent="Auto: "+auto;updateWind()}fetchMarine(lat,lon)}catch(e){$("weatherText").textContent="Meteo non disponibile"}}
async function fetchMarine(lat,lon){try{let r=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&current=wave_height,sea_surface_temperature&forecast_days=1&timezone=auto`);let d=await r.json();let c=d.current||{};marine.wave=c.wave_height??null;marine.water=c.sea_surface_temperature??null;$("marineText").innerHTML=`Mare: ${c.wave_height!=null?c.wave_height+" m onde":"onde n/d"}${c.sea_surface_temperature!=null?" · acqua "+Math.round(c.sea_surface_temperature)+"°C":""}`;render()}catch(e){$("marineText").textContent="Meteo marino non disponibile";render()}}
function updateWind(){state.windMode=$("wind").value;state.effectiveWind=state.windMode==="Automatico dal meteo"?state.autoWind:state.windMode;render()}
function setPreset(){let [lat,lon]=$("originPreset").value.split(",").map(Number);state.manualOrigin={lat,lon,label:$("originPreset").selectedOptions[0].textContent};map.setView([lat,lon],9);fetchWeather(lat,lon,state.manualOrigin.label,true)}
function setManual(){let m=$("manualCoords").value.match(/(-?\\d+(\\.\\d+)?)\\s*,\\s*(-?\\d+(\\.\\d+)?)/);if(m){state.manualOrigin={lat:Number(m[1]),lon:Number(m[3]),label:"coordinate manuali"};map.setView([state.manualOrigin.lat,state.manualOrigin.lon],9);fetchWeather(state.manualOrigin.lat,state.manualOrigin.lon,"coordinate manuali",true)}}
function updateOrigin(){state.originMode=$("originMode").value;if(state.originMode==="base")fetchWeather(BASE.lat,BASE.lon,"La Caletta",true);else if(state.originMode==="preset")setPreset();else if(state.originMode==="manual")setManual();else locate();render()}
function locate(){if(!navigator.geolocation){alert("Geolocalizzazione non disponibile");return}navigator.geolocation.getCurrentPosition(pos=>{state.userLocation={lat:pos.coords.latitude,lon:pos.coords.longitude,label:"GPS"};if(!userMarker)userMarker=L.circleMarker([state.userLocation.lat,state.userLocation.lon],{radius:8,color:"#fff",fillColor:"#ef4444",fillOpacity:1}).addTo(map).bindPopup("Sei qui");else userMarker.setLatLng([state.userLocation.lat,state.userLocation.lon]);map.setView([state.userLocation.lat,state.userLocation.lon],10);$("originMode").value="gps";state.originMode="gps";fetchWeather(state.userLocation.lat,state.userLocation.lon,"la tua posizione",true);render()},()=>alert("Non riesco a leggere la posizione"),{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function bind(){document.querySelectorAll(".intent").forEach(b=>b.addEventListener("click",()=>setIntent(b.dataset.intent)));document.querySelectorAll(".bottomnav button").forEach(b=>b.addEventListener("click",()=>{setIntent(b.dataset.intent);window.scrollTo({top:0,behavior:"smooth"})}));$("smartSearch").addEventListener("input",e=>{state.query=e.target.value;render()});$("quickSearch").addEventListener("input",e=>{state.quickFilter=e.target.value;render()});$("sortMode").addEventListener("input",e=>{state.sortMode=e.target.value;render()});$("wind").addEventListener("input",updateWind);$("driveMax").addEventListener("input",()=>{state.driveMax=Number($("driveMax").value);$("driveLabel").textContent=state.driveMax+" min";render()});$("walkMax").addEventListener("input",()=>{state.walkMax=Number($("walkMax").value);$("walkLabel").textContent=state.walkMax+" min";render()});$("crowd").addEventListener("input",e=>{state.crowd=e.target.value;render()});$("personalPref").addEventListener("input",e=>{state.personalPref=e.target.value;render()});["withinDriveOnly","hideVisited","favoritesOnly"].forEach(id=>$(id).addEventListener("change",()=>{state[id]=$(id).checked;render()}));$("originMode").addEventListener("change",updateOrigin);$("originPreset").addEventListener("change",()=>{$("originMode").value="preset";state.originMode="preset";setPreset();render()});$("manualCoords").addEventListener("change",()=>{$("originMode").value="manual";state.originMode="manual";setManual();render()});$("locateBtn").addEventListener("click",locate);$("todayBtn").addEventListener("click",today);$("weatherOrigin").addEventListener("click",()=>fetchWeather(origin().lat,origin().lon,origin().label||"partenza",true));$("closeDialog").addEventListener("click",()=>$("placeDialog").close());$("chatSend").addEventListener("click",chatSend);$("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")chatSend()})}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn")?.addEventListener("click",async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$("installBtn").classList.add("hidden")}});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
loadLocal();initMap();bind();fetchWeather(BASE.lat,BASE.lon,"La Caletta",true);
