
const $=id=>document.getElementById(id);
const BASE={lat:40.6096,lon:9.7514,label:"La Caletta"};
let state={mode:"balanced",origin:BASE,originType:"base",wind:"Mare calmo",autoWind:"Mare calmo",driveMax:120,walkMax:20,sort:"ai",query:"",quietOnly:false,withinDriveOnly:true,favoritesOnly:false,hideVisited:false};
let marine={wave:null,water:null};
const icon={"Snorkeling elite":"🤿","Snorkeling PRO":"🐠","Calette nascoste":"🏝️","Spiagge top":"🏖️","Panorami/foto":"📸","Escursioni/gommoni":"🚤","Cibo/pesce":"🍝","Parcheggi/accessi":"🅿️","Spiagge famose":"⭐","Spiagge famose Nord":"💎","Spiagge famose Sud":"🌅","Iconiche Golfo Orosei":"🌊","Spiagge Sardegna Nord-Ovest":"🧭","Spiagge Sardegna Nord":"🧭","Spiagge Sardegna Ovest":"🌊","Spiagge Sardegna Sud-Ovest":"🌅","Spiagge Sardegna Sud":"🌞","Spiagge Sardegna Sud-Est":"🌞","Spiagge Sardegna Est":"🌊"};
const mapsIcon='<svg class="mapicon" viewBox="0 0 24 24"><path fill="#34a853" d="M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7z"/><circle fill="#fff" cx="12" cy="9" r="2.5"/></svg>';
const wazeIcon='<svg class="mapicon" viewBox="0 0 24 24"><path fill="#33ccff" d="M20 11.5c0-4.1-3.6-7.5-8-7.5s-8 3.4-8 7.5c0 1.5.5 2.9 1.4 4.1L3 18h3.6c1.4.7 3.2 1 5.4 1 4.4 0 8-3.4 8-7.5z"/><circle cx="9" cy="11" r="1"/><circle cx="15" cy="11" r="1"/><path d="M9 15c2 1 4 1 6 0" stroke="#111" fill="none" stroke-width="1.5"/></svg>';
function loadLocal(){try{const s=JSON.parse(localStorage.getItem("sardegna-v8")||"{}");PLACES.forEach(p=>{if(s.favorites?.[p.id])p.favorite=true;if(s.visited?.[p.id])p.visited=true;if(s.notes?.[p.id])p.personalNote=s.notes[p.id]})}catch(e){}}
function saveLocal(){const favorites={},visited={},notes={};PLACES.forEach(p=>{if(p.favorite)favorites[p.id]=true;if(p.visited)visited[p.id]=true;if(p.personalNote)notes[p.id]=p.personalNote});localStorage.setItem("sardegna-v8",JSON.stringify({favorites,visited,notes}))}
function hav(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180;const dp=rad(c-a),dl=rad(d-b);const q=Math.sin(dp/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function dist(p){return hav(state.origin.lat,state.origin.lon,p.lat,p.lon)}
function drive(p){return Math.round((dist(p)*1.38/62)*60+8)}
function seaScore(p){let s=10;if(marine.wave!=null){if(marine.wave>1.2)s-=3;else if(marine.wave>.7)s-=1.5}if((p.windAvoid||"").includes(state.wind))s-=2;if((p.windOK||"").includes(state.wind))s+=.8;return Math.max(0,Math.min(10,Math.round(s*10)/10))}
function textScore(p,q){if(!q)return 0;q=q.toLowerCase();const hay=`${p.name} ${p.zone} ${p.category} ${p.fauna} ${p.notes} ${(p.tags||[]).join(" ")}`.toLowerCase();let s=0;q.split(/\s+/).filter(Boolean).forEach(w=>{if(hay.includes(w))s+=8;if(p.name.toLowerCase().includes(w))s+=16});if(q.includes("liberotto")&&p.name.toLowerCase().includes("liberotto"))s+=60;if(q.includes("polp")&&hay.includes("polp"))s+=20;if(q.includes("tramonto")&&hay.includes("tramonto"))s+=16;return s}
function score(p){let s=p.wow*1.6+p.waterColor*.7+p.snorkeling*.7+seaScore(p)*1.2+textScore(p,state.query);if(state.mode==="wow")s+=p.wow*1.8+p.waterColor*1.4;if(state.mode==="snorkel")s+=p.snorkeling*2.4+(String(p.tags||"").includes("snorkeling")?8:0);if(state.mode==="balanced")s+=p.wow+p.snorkeling*.8-(drive(p)/20)-(p.walkMin/8);if((p.windOK||"").includes(state.wind))s+=6;if((p.windAvoid||"").includes(state.wind))s-=12;s+=(drive(p)<=state.driveMax)?8:-(drive(p)-state.driveMax)/2;s+=(p.walkMin<=state.walkMax)?6:-8;if(state.quietOnly)s+=(p.crowdTarget==="Tranquillo"?10:-4);if(state.withinDriveOnly&&drive(p)>state.driveMax)s-=1000;if(state.favoritesOnly&&!p.favorite)s-=1000;if(state.hideVisited&&p.visited)s-=1000;return Math.round(s*10)/10}
function results(){let arr=PLACES.map(p=>({...p,aiScore:score(p),distanceKm:dist(p),driveMin:drive(p),seaScore:seaScore(p)})).filter(p=>p.aiScore>-50);if(state.sort==="distance")arr.sort((a,b)=>a.distanceKm-b.distanceKm||b.aiScore-a.aiScore);else if(state.sort==="rating")arr.sort((a,b)=>b.wow-a.wow||b.aiScore-a.aiScore);else arr.sort((a,b)=>b.aiScore-a.aiScore||a.distanceKm-b.distanceKm);return arr}
function why(p){const bits=[];if(state.mode==="snorkel"&&p.snorkeling>=7)bits.push("buono per snorkeling");if(state.mode==="wow"&&p.wow>=9)bits.push("mare wow");if((p.windOK||"").includes(state.wind))bits.push("vento favorevole");if(drive(p)<=state.driveMax)bits.push("entro tempo auto");if(p.walkMin<=state.walkMax)bits.push("camminata ok");if(p.name.toLowerCase().includes("liberotto"))bits.push("ottimi scogli laterali");return bits.slice(0,4).join(" · ")||"buon equilibrio generale"}
function gmaps(p){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.lat+","+p.lon)}&travelmode=driving`}
function waze(p){return `https://waze.com/ul?ll=${p.lat},${p.lon}&navigate=yes`}
function mcolor(c){if((c||"").includes("Snorkeling"))return"#38bdf8";if(c==="Calette nascoste")return"#22c55e";if(c==="Panorami/foto")return"#fb923c";if(c==="Cibo/pesce")return"#fb7185";if((c||"").includes("famose")||(c||"").includes("Iconiche")||(c||"").includes("Sardegna"))return"#fbbf24";return"#94a3b8"}
function makeIcon(p){return L.divIcon({className:"custom-marker",html:`<div style="width:30px;height:30px;border-radius:50%;background:${mcolor(p.category)};display:grid;place-items:center;border:2px solid white;box-shadow:0 8px 20px rgba(0,0,0,.35);font-size:16px">${icon[p.category]||"📍"}</div>`,iconSize:[30,30],iconAnchor:[15,15],popupAnchor:[0,-12]})}
let map,layer,userMarker;
function initMap(){map=L.map("map",{zoomControl:false}).setView([40.45,9.45],8);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(map);layer=L.layerGroup().addTo(map)}
function renderMarkers(list){layer.clearLayers();list.slice(0,160).forEach(p=>L.marker([p.lat,p.lon],{icon:makeIcon(p)}).addTo(layer).bindPopup(`<b>${icon[p.category]||"📍"} ${p.name}</b><br>${p.driveMin} min · AI ${p.aiScore}<br><button onclick="openDetail('${p.id}')">Apri</button>`))}
function render(){const list=results();$("totalPlaces").textContent=PLACES.length;$("resultsTitle").textContent=`Risultati · ${list.length}`;renderMarkers(list);$("results").innerHTML=list.slice(0,60).map((p,i)=>`<article class="card"><h4>${i+1}. ${icon[p.category]||"📍"} ${p.name}</h4><div class="meta">${p.zone} · ${p.category}<br>${p.distanceKm.toFixed(1)} km · 🚗 ${p.driveMin} min · 🚶 ${p.walkMin} min</div><div class="score"><span class="pill gold">AI ${p.aiScore}</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span><span class="pill">mare ${p.seaScore}/10</span></div><div class="meta">Perché: <b>${why(p)}</b></div><div class="actions"><button onclick="openDetail('${p.id}')">Scheda</button><a class="ghost" href="${gmaps(p)}" target="_blank">${mapsIcon}Maps</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a><button class="ghost" onclick="toggleFavorite('${p.id}')">${p.favorite?'★':'☆'} Preferito</button></div></article>`).join("")}
function today(){const p=results()[0];if(!p)return;$("todayChoice").classList.remove("hidden");$("todayChoice").innerHTML=`<h3>🏆 Oggi ti porterei a: ${p.name}</h3><div class="score"><span class="pill gold">AI ${p.aiScore}</span><span class="pill">🚗 ${p.driveMin} min</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span></div><p class="meta">${why(p)}</p><div class="actions"><button onclick="openDetail('${p.id}')">Scheda</button><a class="primary" href="${gmaps(p)}" target="_blank">${mapsIcon}Portami lì</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a></div>`}
function openDetail(id){const p=PLACES.find(x=>x.id===id);if(!p)return;fetchWeather(p.lat,p.lon,p.name,false);$("placeDetail").innerHTML=`<div><h2>${icon[p.category]||"📍"} ${p.name}</h2><p class="meta">${p.zone}<br>${dist(p).toFixed(1)} km · 🚗 ${drive(p)} min · 🚶 ${p.walkMin} min</p><div class="score"><span class="pill gold">AI ${score(p)}</span><span class="pill">🤿 ${p.snorkeling}/10</span><span class="pill">WOW ${p.wow}/10</span></div><div class="detail-grid"><div class="detail-box"><b>Perché</b>${why(p)}</div><div class="detail-box"><b>Fauna</b>${p.fauna||"-"}</div><div class="detail-box"><b>Vento OK</b>${p.windOK||"-"}</div><div class="detail-box"><b>Evita con</b>${p.windAvoid||"-"}</div><div class="detail-box"><b>Ingresso</b>${p.entryTip||"-"}</div><div class="detail-box"><b>Parcheggio</b>${p.parking||"-"}</div></div><p>${p.notes||""}</p><textarea id="noteBox" placeholder="Nota personale / diario...">${p.personalNote||""}</textarea><div class="actions" style="margin-top:12px"><a class="primary" href="${gmaps(p)}" target="_blank">${mapsIcon}Google Maps</a><a class="ghost" href="${waze(p)}" target="_blank">${wazeIcon}Waze</a><button class="ghost" onclick="toggleFavorite('${p.id}')">${p.favorite?'★ Preferito':'☆ Preferito'}</button><button class="ghost" onclick="toggleVisited('${p.id}')">${p.visited?'Visitato ✓':'Segna visitato'}</button><button onclick="saveNote('${p.id}')">Salva nota</button></div></div>`;$("placeDialog").showModal()}
window.openDetail=openDetail;function toggleFavorite(id){const p=PLACES.find(x=>x.id===id);if(p){p.favorite=!p.favorite;saveLocal();render()}}function toggleVisited(id){const p=PLACES.find(x=>x.id===id);if(p){p.visited=!p.visited;saveLocal();render()}}function saveNote(id){const p=PLACES.find(x=>x.id===id);if(p){p.personalNote=$("noteBox").value;saveLocal();render()}}window.toggleFavorite=toggleFavorite;window.toggleVisited=toggleVisited;window.saveNote=saveNote;
function setMode(mode){state.mode=mode;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));render()}
function setOrigin(type){state.originType=type;document.querySelectorAll(".seg").forEach(b=>b.classList.remove("active"));if(type==="base"){$("useBase").classList.add("active");state.origin=BASE;$("manualOriginBox").classList.add("hidden");$("originStatus").textContent="Partenza: La Caletta";map.setView([BASE.lat,BASE.lon],8);fetchWeather(BASE.lat,BASE.lon,"La Caletta",true);render()}if(type==="manual"){$("useManual").classList.add("active");$("manualOriginBox").classList.remove("hidden")}if(type==="gps"){locate()}}
function applyPreset(){const [lat,lon]=$("originPreset").value.split(",").map(Number);state.origin={lat,lon,label:$("originPreset").selectedOptions[0].textContent};$("originStatus").textContent="Partenza: "+state.origin.label;map.setView([lat,lon],9);fetchWeather(lat,lon,state.origin.label,true);render()}
function applyCoords(){const m=$("manualCoords").value.match(/(-?\d+(\.\d+)?)\s*,\s*(-?\d+(\.\d+)?)/);if(m){state.origin={lat:Number(m[1]),lon:Number(m[3]),label:"coordinate manuali"};$("originStatus").textContent="Partenza: coordinate manuali";map.setView([state.origin.lat,state.origin.lon],9);fetchWeather(state.origin.lat,state.origin.lon,"coordinate manuali",true);render()}}
function locate(){if(!navigator.geolocation){alert("Geolocalizzazione non disponibile");return}navigator.geolocation.getCurrentPosition(pos=>{state.origin={lat:pos.coords.latitude,lon:pos.coords.longitude,label:"GPS preciso"};$("useGps").classList.add("active");$("useBase").classList.remove("active");$("useManual").classList.remove("active");$("manualOriginBox").classList.add("hidden");$("originStatus").textContent="Partenza: GPS preciso";if(!userMarker)userMarker=L.circleMarker([state.origin.lat,state.origin.lon],{radius:8,color:"#fff",fillColor:"#ef4444",fillOpacity:1}).addTo(map).bindPopup("Sei qui");else userMarker.setLatLng([state.origin.lat,state.origin.lon]);map.setView([state.origin.lat,state.origin.lon],10);fetchWeather(state.origin.lat,state.origin.lon,"la tua posizione",true);render()},()=>alert("Non riesco a leggere la posizione. Controlla i permessi."),{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function windName(deg,speed){if(speed>=25)return"Vento forte";if(deg==null)return"Mare calmo";let d=["N","NE","E","SE","S","SW","W","NW"][Math.round(deg/45)%8];if(d==="NW")return speed>=15?"Maestrale forte":"Maestrale leggero";if(d==="SE")return speed>=15?"Scirocco forte":"Scirocco leggero";if(d==="E")return"Levante forte";if(d==="W")return"Ponente leggero";return speed<8?"Mare calmo":"Vento forte"}
function windDir(deg){if(deg==null)return"-";return["N","NE","E","SE","S","SW","W","NW"][Math.round(deg/45)%8]}
async function fetchWeather(lat,lon,label,update){try{let r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,wind_direction_10m&forecast_days=1&timezone=auto`);let d=await r.json();let c=d.current||{};let sp=Math.round(c.wind_speed_10m||0);state.autoWind=windName(c.wind_direction_10m,sp);state.wind=state.autoWind;$("weatherText").innerHTML=`<b>${label}</b>: ${Math.round(c.temperature_2m)}°C · vento ${sp} km/h da ${windDir(c.wind_direction_10m)} · ${state.autoWind}`;fetchMarine(lat,lon)}catch(e){$("weatherText").textContent="Meteo non disponibile"}}
async function fetchMarine(lat,lon){try{let r=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&current=wave_height,sea_surface_temperature&forecast_days=1&timezone=auto`);let d=await r.json();let c=d.current||{};marine.wave=c.wave_height??null;marine.water=c.sea_surface_temperature??null;$("marineText").innerHTML=`Mare: ${c.wave_height!=null?c.wave_height+" m onde":"onde n/d"}${c.sea_surface_temperature!=null?" · acqua "+Math.round(c.sea_surface_temperature)+"°C":""}`;render()}catch(e){$("marineText").textContent="Meteo marino non disponibile";render()}}
function chatSend(){const t=$("chatInput").value.trim();if(!t)return;$("chatLog").innerHTML+=`<div class="user">${t}</div>`;$("chatInput").value="";const s=t.toLowerCase();state.query=s;$("textSearch").value=s;if(s.match(/snork|pesci|polp|maschera/))setMode("snorkel");else if(s.match(/wow|bello|turchese|cristall/))setMode("wow");else setMode("balanced");const mins=s.match(/(\d+)\s*(min|minuti|ora|ore|h)/);if(mins){let n=Number(mins[1]);if(s.includes("ora")||s.includes("ore")||s.includes("h"))n*=60;state.driveMax=n;$("driveMax").value=Math.min(260,n);$("driveLabel").textContent=n+" min"}const top=results().slice(0,3);$("chatLog").innerHTML+=`<div class="bot">Ok, ti ho aggiornato la ricerca. Ti direi:<br><br>${top.map((p,i)=>`${i+1}. <b>${p.name}</b> · 🚗 ${p.driveMin} min · 🤿 ${p.snorkeling}/10 · WOW ${p.wow}/10<br><small>${why(p)}</small>`).join("<br><br>")}<br><br>Puoi continuare con “più vicino”, “meno camminata”, “più mare wow”.</div>`;$("chatLog").scrollTop=$("chatLog").scrollHeight;render()}
function bind(){document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));document.querySelectorAll(".bottomnav button[data-mode]").forEach(b=>b.addEventListener("click",()=>{setMode(b.dataset.mode);window.scrollTo({top:0,behavior:"smooth"})}));$("navChat").addEventListener("click",()=>document.querySelector(".assistant-card").scrollIntoView({behavior:"smooth"}));$("useBase").addEventListener("click",()=>setOrigin("base"));$("useGps").addEventListener("click",()=>setOrigin("gps"));$("useManual").addEventListener("click",()=>setOrigin("manual"));$("originPreset").addEventListener("change",applyPreset);$("manualCoords").addEventListener("change",applyCoords);$("driveMax").addEventListener("input",()=>{state.driveMax=Number($("driveMax").value);$("driveLabel").textContent=state.driveMax+" min";render()});$("walkMax").addEventListener("input",()=>{state.walkMax=Number($("walkMax").value);$("walkLabel").textContent=state.walkMax+" min";render()});$("textSearch").addEventListener("input",()=>{state.query=$("textSearch").value;render()});$("sortMode").addEventListener("input",()=>{state.sort=$("sortMode").value;render()});["quietOnly","withinDriveOnly","favoritesOnly","hideVisited"].forEach(id=>$(id).addEventListener("change",()=>{state[id]=$(id).checked;render()}));$("refreshWeather").addEventListener("click",()=>fetchWeather(state.origin.lat,state.origin.lon,state.origin.label||"partenza",true));$("todayBtn").addEventListener("click",today);$("closeDialog").addEventListener("click",()=>$("placeDialog").close());$("chatSend").addEventListener("click",chatSend);$("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")chatSend()})}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn")?.addEventListener("click",async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$("installBtn").classList.add("hidden")}});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
loadLocal();initMap();bind();fetchWeather(BASE.lat,BASE.lon,"La Caletta",true);
